@extends("property.layouts.main")
@section("main-container")
<div class="container-fluid"><div class="row"><div class="col-12"><div class="card"><div class="card-header"><h4>Due List — Customers</h4><p class="text-muted mb-0">Customer outstanding ledger detail (legacy: DUELIST)</p></div><div class="card-body"><div class="row g-3 mb-3"><div class="col-md-2"><label>To Date</label><input type="date" class="form-control" id="todate" value="{{ $todate }}"></div><div class="col-md-2 d-flex align-items-end"><button type="button" class="btn btn-primary me-2" onclick="fetchData()"><i class="fas fa-search"></i> Fetch</button><button type="button" class="btn btn-success" onclick="exportExcel()"><i class="fas fa-file-excel"></i> Excel</button></div></div><div class="table-responsive"><table id="reportTable" class="table table-striped table-bordered table-sm" style="width:100%"><thead class="thead-dark"><tr id="headerRow"></tr></thead><tbody id="reportBody"></tbody></table></div></div></div></div></div>
<script>
var table=null;
$(document).ready(function(){table=$("#reportTable").DataTable({dom:"Bfrtip",buttons:["excel","print"],pageLength:25,order:[]});fetchData();});
function fetchData(){var d={_token:$("meta[name=csrf-token]").attr("content")};if($("#fromdate").length)d.fromdate=$("#fromdate").val();if($("#todate").length)d.todate=$("#todate").val();if($("#searchInput").length)d.search=$("#searchInput").val();$.post("duelist.fetch",d,function(r){table.clear();if(r.success&&r.data.length>0){var keys=Object.keys(r.data[0]);$("#headerRow").html(keys.map(function(k){return"<th>"+k.toUpperCase().replace(/_/g," ")+"</th>"}).join(""));$.each(r.data,function(i,row){var tr="<tr>";keys.forEach(function(k){var v=row[k];tr+="<td>"+(typeof v=="number"?fmt(v):(v||""))+"</td>"});tr+="</tr>";table.row.add($(tr)).draw(false)})}table.draw()},"json")}
function exportExcel(){$(".buttons-excel").click()}
</script>
@endsection